### ISSUE TITLE
bottom of a vertical wide path cut is flat instead of rounded

### ISSUE THREAD

**Issue by sir-buckyball** [sir-buckyball/opencut#62]
The rendering of the following code indicates a flat bottom to the hole instead of the expected rounded hole.
![bug](https://cloud.githubusercontent.com/assets/1843109/15018272/c3162616-11cd-11e6-95d6-c09ab4035d8e.png)

```
units: inch
bit_diameter: 0.125
default_depth: -0.75
z_step_size: 0.15
cuts:
  - type: screwpath
    shaft_diameter: 0.425
    shaft_depth: -0.75
    points:
      - [0.25, 0.25]
      - [0.25, 1.75]
  - type: profile
    side: outside
    shape:
      type: rectangle
      origin: [0, 0]
      size: [0.5, 2]
```
